services:
  - type: web
    name: talabat-area-scraper-api
    env: docker
    dockerfilePath: ./Dockerfile.api
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: SCRAPER_WALL_CLOCK_SEC
        value: "600"
